---

- hosts: all
  tasks:
    - name: Install EPEL repo
      yum_repository:
        name: "{{ item.name }}"
        description: "{{ item.descr }}"
        baseurl: "{{ item.baseurl }}"
      with_items:
        - { name: 'epel', descr: 'EPEL YUM repo', baseurl: 'https://download.fedoraproject.org/pub/epel/$releasever/$basearch/' }